import test from 'node:test';import assert from 'node:assert/strict';import {bech32} from '@scure/base';import {decodeEscrowAddress,planApprovalEscrow} from '../src/adapters/approval-escrow-plan.mjs';
const address=(key,kind=6,network=0,stake=3)=>bech32.encode(network?'addr':'addr_test',bech32.toWords(Uint8Array.from([kind*16+network,...Array(28).fill(key),...([0,2].includes(kind)?Array(28).fill(stake):[])])),200);
const intent=()=>({network:'cardano:preprod',objectiveId:'objective',effectId:'effect',semanticKey:'one-report',principalAddress:address(1,0),providerAddress:address(2,2),artifactSha256:'a'.repeat(64),nonceHex:'b'.repeat(64),amountLovelace:3000000,fundingFeeBudgetLovelace:250000,closingFeeBudgetLovelace:250000,collateralExposureLovelace:500000,maxExposureLovelace:5000000,minimumOutputLovelace:2000000});
test('checksum, full stake credentials and restricted network/types are validated',()=>{assert.equal(decodeEscrowAddress(address(1,0)).stake.kind,'key');assert.equal(decodeEscrowAddress(address(1,2)).stake.kind,'script');assert.equal(decodeEscrowAddress(address(1)).stake,null);for(const value of [address(1).slice(0,-1)+'x',address(1,6,1),address(1).toUpperCase(),address(1,7),'addr_test1fixture'])assert.throws(()=>decodeEscrowAddress(value));});
test('plan binds datum and full payouts without enabling signing or dispatch',()=>{const p=planApprovalEscrow(intent());assert.equal(p.datum.fields.length,6);assert.deepEqual(p.datum.fields[0],{int:1});assert.equal(p.signers.accept.length,2);assert.equal(p.requiredPayouts.accept.address,intent().providerAddress);assert.equal(p.funding.totalExposureLovelace,4000000);assert.equal(p.dispatchAllowed,false);assert.equal(p.globalMandateEnforcedOnChain,false);});
test('different effects, staking addresses and artifact hashes change intent binding',()=>{const first=planApprovalEscrow(intent());for(const patch of [{effectId:'other'},{providerAddress:address(2,2,0,4)},{artifactSha256:'c'.repeat(64)},{nonceHex:'d'.repeat(64)}])assert.notEqual(planApprovalEscrow({...intent(),...patch}).intentSha256,first.intentSha256);assert.deepEqual(planApprovalEscrow(Object.fromEntries(Object.entries(intent()).reverse())),first);});
test('rejects fee budget overflow, below minimum, forged flags, asset substitutions and identical payment keys',()=>{for(const patch of [{maxExposureLovelace:3000000},{minimumOutputLovelace:4000000},{amountLovelace:0.5},{closingFeeBudgetLovelace:0},{network:'cardano:mainnet'},{dispatchAllowed:true},{principalAddress:address(2,0)},{nonceHex:'short'}])assert.throws(()=>planApprovalEscrow({...intent(),...patch}));});

test('planner datum/redeemers conform recursively to compiled Aiken blueprint',async()=>{
 const {readFile}=await import('node:fs/promises');const {createHash}=await import('node:crypto');const root='contracts/approval-escrow',blueprint=JSON.parse(await readFile(`${root}/plutus.json`)),receipt=JSON.parse(await readFile(`${root}/verification.json`));
 for(const [file,expected] of Object.entries(receipt.sourceAndArtifactSha256))assert.equal(createHash('sha256').update(await readFile(`${root}/${file}`)).digest('hex'),expected,`Artifact drift: ${file}`);
 const deref=ref=>blueprint.definitions[ref.slice('#/definitions/'.length).replaceAll('~1','/').replaceAll('~0','~')];
 function validate(value,schema){if(schema.$ref)return validate(value,deref(schema.$ref));if(schema.anyOf){const variant=schema.anyOf.find(v=>v.index===value.constructor);assert.ok(variant,'Unknown constructor');return validate(value,variant);}if(schema.dataType==='constructor'){assert.equal(value.constructor,schema.index);assert.equal(value.fields.length,schema.fields.length);value.fields.forEach((f,i)=>validate(f,schema.fields[i]));}else if(schema.dataType==='bytes')assert.match(value.bytes,/^(?:[a-f0-9]{2})*$/);else if(schema.dataType==='integer')assert.ok(Number.isSafeInteger(value.int));else assert.fail('Unsupported schema');}
 const validator=blueprint.validators.find(v=>v.title.endsWith('.spend'));const protocol=planApprovalEscrow(intent()).protocol;assert.equal(protocol.scriptHash,validator.hash);assert.equal(protocol.blueprintSha256,receipt.sourceAndArtifactSha256['plutus.json']);const scriptBytes=bech32.fromWords(bech32.decode(protocol.scriptAddress,200).words);assert.equal(scriptBytes[0],0x70);assert.equal(Buffer.from(scriptBytes).subarray(1).toString('hex'),validator.hash);for(const kind of [0,2,6]){const plan=planApprovalEscrow({...intent(),principalAddress:address(1,kind),providerAddress:address(2,kind)});validate(plan.datum,validator.datum.schema);validate(plan.redeemers.accept,validator.redeemer.schema);validate(plan.redeemers.cancel,validator.redeemer.schema);}
 assert.equal(receipt.deployed,false);assert.equal(receipt.testSummary.failed,0);
});
