import test from 'node:test';import assert from 'node:assert/strict';import {revalidateCardanoObservation} from '../src/adapters/cardano-observation.mjs';
import {observeDraftTransaction} from '../src/adapters/cardano-first-observation.mjs';
const txHash='a'.repeat(64),blockHash='b'.repeat(64),observation={network:'cardano:preprod',txHash,blockHash,blockHeight:100};
const run=async(tx={},tip={},ok=true)=>{const calls=[];const result=await revalidateCardanoObservation({observation,projectId:'test-credential',fetchImpl:async(url,opts)=>{calls.push({url,opts});return new Response(JSON.stringify(url.endsWith('/blocks/latest')?{height:103,hash:'c'.repeat(64),...tip}:{hash:txHash,block:blockHash,block_height:100,valid_contract:true,...tx}),{status:ok?200:503});}});assert.ok(calls.every(c=>c.url.startsWith('https://cardano-preprod.blockfrost.io/api/v0/')&&c.opts.redirect==='error'));assert.equal(result.exposureReleaseAllowed,false);assert.equal(result.automaticRetryAllowed,false);assert.ok(!JSON.stringify(result).includes('test-credential'));return result;};
test('unchanged sufficiently confirmed observation reports indexer evidence only',async()=>assert.equal((await run()).status,'STILL_OBSERVED'));
test('re-inclusion, block changes, invalid contract and lower tip require review without release',async()=>{for(const [tx,tip] of [[{block:'d'.repeat(64)},{}],[{block_height:101},{}],[{valid_contract:false},{}],[{},{height:99}],[{},{height:100}]])assert.equal((await run(tx,tip)).status,'REVIEW_REQUIRED');});
test('missing/invalid/provider failures remain UNKNOWN, never prove rollback or refund',async()=>{assert.equal((await run({}, {},false)).status,'UNKNOWN');assert.equal((await run({hash:'wrong'})).status,'UNKNOWN');const missing=await revalidateCardanoObservation({observation,projectId:''});assert.equal(missing.reason,'NOT_CONFIGURED');assert.equal(missing.automaticDispatchBlocked,true);});
test('rejects network and immutable binding substitutions before fetch',async()=>{let calls=0;for(const patch of [{network:'cardano:mainnet'},{blockHash:''},{blockHeight:-1},{txHash:'https://evil'}])await assert.rejects(revalidateCardanoObservation({observation:{...observation,...patch},projectId:'x',fetchImpl:async()=>calls++}));assert.equal(calls,0);});
test('caller mutation during asynchronous lookup cannot replace the original block binding',async()=>{const mutable={...observation};let release;const gate=new Promise(resolve=>release=resolve);const pending=revalidateCardanoObservation({observation:mutable,projectId:'x',fetchImpl:async url=>{await gate;return new Response(JSON.stringify(url.endsWith('/blocks/latest')?{height:104,hash:'c'.repeat(64)}:{hash:txHash,block:'d'.repeat(64),block_height:101,valid_contract:true}));}});mutable.blockHash='d'.repeat(64);mutable.blockHeight=101;release();const r=await pending;assert.equal(r.status,'REVIEW_REQUIRED');assert.equal(r.automaticDispatchBlocked,true);assert.equal(r.exposureReleaseAllowed,false);});
test('confirmation arithmetic rejects unsafe counts',async()=>{const r=await revalidateCardanoObservation({observation:{...observation,blockHeight:0},projectId:'x',fetchImpl:async url=>new Response(JSON.stringify(url.endsWith('/blocks/latest')?{height:Number.MAX_SAFE_INTEGER,hash:'c'.repeat(64)}:{hash:txHash,block:blockHash,block_height:0,valid_contract:true}))});assert.equal(r.status,'UNKNOWN');assert.equal(r.automaticDispatchBlocked,true);});
test('oversized, redirected, foreign-origin and malformed provider bytes cannot confirm funding or closing',async()=>{
 const factories=[()=>new Response('x'.repeat(262145)),()=>new Response('{invalid'),()=>{
   const r=new Response('{}');Object.defineProperty(r,'redirected',{value:true});return r;
 },()=>{const r=new Response('{}');Object.defineProperty(r,'url',{value:'https://foreign.example/tx'});return r;}];
 for(const factory of factories){
  assert.equal((await revalidateCardanoObservation({observation,projectId:'fixture',fetchImpl:async()=>factory()})).status,'UNKNOWN');
  assert.equal((await observeDraftTransaction({txHash,projectId:'fixture',fetchImpl:async()=>factory()})).status,'UNKNOWN');
 }
});
