import test from 'node:test';
import assert from 'node:assert/strict';
import {CompanyRuntime,simulatedProvider} from '../src/company/runtime.mjs';
import {exportHandoff,checkHandoff,interoperabilityCapabilities} from '../src/company/handoff.mjs';
async function setup(){const runtime=new CompanyRuntime(':memory:');runtime.create({id:'m',objectiveId:'o',principal:'p',semanticKey:'s',brief:'Supplied fixture only',evidence:[{id:'ref',kind:'fixture',content:'Synthetic',source:'local'}]});await runtime.runTask('m','plan/scope',simulatedProvider);const s=runtime.snapshot('m');runtime.close();const envelope=exportHandoff(s,'plan/scope');return {snapshot:s,envelope,expected:{digest:envelope.digest,missionId:'m',taskId:'plan/scope',agentId:'chief-of-staff/scope',policyDigest:s.policyDigest,evidenceIds:['ref']}};}
test('handoff checks trusted identity and digest without creating verified claims',async()=>{const {envelope,expected}=await setup();const checked=checkHandoff(envelope,expected);assert.equal(checked.integrityValid,true);assert.equal(checked.authenticated,false);assert.equal(checked.record.executionMode,'simulation');assert.equal(checked.authority,'advisory-only');assert.equal(interoperabilityCapabilities().paymentAuthority,false);});
test('tampered content, foreign identity and authority injection are rejected',async()=>{for(const mutate of [e=>e.record.summary='changed',e=>e.record.missionId='other',e=>e.record.verified=true,e=>e.record.authority='payment',e=>e.record.evidenceRefs=['unknown']]){const {envelope,expected}=await setup();mutate(envelope);assert.throws(()=>checkHandoff(envelope,expected));}});
test('a caller-supplied digest is not a trusted receipt',async()=>{const {envelope,expected}=await setup();assert.throws(()=>checkHandoff(envelope,{...expected,digest:undefined}),/digest/);assert.throws(()=>checkHandoff(envelope,{...expected,agentId:'risk'}),/identity/);assert.throws(()=>checkHandoff(envelope,{...expected,evidenceIds:[]}),/catalog/);});

test('handoff export refuses changed task owner and extra authority fields in stored output',async()=>{for(const mutate of [o=>o.agentId='risk',o=>o.verified=true]){const {snapshot}=await setup();mutate(snapshot.tasks.find(t=>t.taskId==='plan/scope').output);assert.throws(()=>exportHandoff(snapshot,'plan/scope'),/binding|fields/);}});
