import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {describeMasumiOperation,inspectMasumiContract,MASUMI_SPEC_URL} from '../src/adapters/masumi-contract.mjs';
const manifest=JSON.parse(readFileSync(new URL('../research/contracts/masumi-5fccf58.json',import.meta.url)));
test('published contract distinguishes POST reads from financial and admin mutations',()=>{assert.equal(describeMasumiOperation(manifest,'POST','/purchase/resolve-blockchain-identifier').category,'read');assert.equal(describeMasumiOperation(manifest,'POST','/purchase/').category,'payment-write');assert.equal(describeMasumiOperation(manifest,'POST','/api-key/').category,'administrative-write');assert.equal(describeMasumiOperation(manifest,'GET','/health/').authentication,'public');assert.equal(manifest.operations.length,29);});
test('raw schema inspection refuses wrong pin, tampered bytes and nonraw input',()=>{assert.throws(()=>inspectMasumiContract('{}',{sourceUrl:MASUMI_SPEC_URL.replace('5fcc','d569')}),/pin/);assert.throws(()=>inspectMasumiContract('{}'),/digest/);assert.throws(()=>inspectMasumiContract({}),/bytes/);assert.throws(()=>inspectMasumiContract('x'.repeat(1000001)),/digest/);});
test('operation lookup rejects changed manifest, forged read classification and unknown endpoints',()=>{const altered=structuredClone(manifest);altered.operations.find(o=>o.path==='/purchase/'&&o.method==='POST').category='read';assert.throws(()=>describeMasumiOperation(altered,'POST','/purchase/'),/integrity/);assert.throws(()=>describeMasumiOperation({...manifest,paymentsEnabled:true},'POST','/purchase/'),/manifest/);assert.throws(()=>describeMasumiOperation(manifest,'POST','/purchase/send'),/Unknown/);});
test('required fields, auth and units stay source-specific with no payment authority',()=>{const op=describeMasumiOperation(manifest,'POST','/purchase/');assert.ok(op.request.required.includes('sellerVkey'));assert.ok(op.request.required.includes('identifierFromPurchaser'));assert.deepEqual(op.request.fields.find(f=>f.name==='network').enum,['Preprod','Mainnet']);assert.equal(op.authentication,'token-header');assert.ok(manifest.operations.every(o=>o.paymentAuthority===false));assert.equal(manifest.liveVerified,false);});
