import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {generateKeyPairSync,sign,createHash} from 'node:crypto';
import {OperationStore} from '../src/server/operation-store.mjs';import {deliveryReceiptBytes} from '../src/adapters/delivery-receipt.mjs';
const objective={id:'o',principal:'p',semanticKey:'five-clips',quantity:1,maxExposure:100};
const input={operationId:'op',principal:'p',objectiveId:'o',proposedEffect:{id:'e',semanticKey:'five-clips',provider:'vendor',type:'payment',amount:80,agent:'builder'}};
function setup(path=':memory:',opts){const s=new OperationStore(path,opts);s.transact(k=>k.createObjective(objective));return s;}
function receipt(s){const bytes=Buffer.from('exact accepted bundle');const {publicKey,privateKey}=generateKeyPairSync('ed25519');const expected={keyId:'key-1',principal:'p',objectiveId:'o',effectId:'e',provider:'vendor',jobId:'job-1',artifactSha256:createHash('sha256').update(bytes).digest('hex')};s.bindAcceptedDelivery(expected);const payload={version:'mew-delivery-v1',receiptId:'receipt-1',...expected,issuedAtMs:1000,expiresAtMs:2000};const envelope={payload,signature:sign(null,deliveryReceiptBytes(payload),privateKey).toString('base64url')};return {effectId:'e',envelope,artifactBytes:bytes,trustedPublicKey:publicKey,nowMs:1500};}
test('reservation and outbox insert roll back together',()=>{const s=setup();try{s.db.exec("CREATE TRIGGER fail_outbox BEFORE INSERT ON payment_outbox BEGIN SELECT RAISE(ABORT,'fixture failure'); END;");assert.throws(()=>s.reserveOperation(input));assert.equal(s.read().position('o').exposure,0);assert.equal(s.operation('op'),null);}finally{s.close();}});
test('reopen retains uncertainty and fences concurrent workers',()=>{const dir=mkdtempSync(join(tmpdir(),'mew-op-')),path=join(dir,'db.sqlite');let s=setup(path),other;
try{assert.equal(s.reserveOperation(input).decision,'ALLOW');other=new OperationStore(path);const claimed=s.claimSimulation('op');assert.throws(()=>other.claimSimulation('op'));assert.equal(other.reserveOperation(input).decision,'DEFER');s.close();s=new OperationStore(path);assert.equal(s.recoverInterrupted(),1);assert.equal(s.operation('op').status,'UNKNOWN');assert.equal(s.read().position('o').exposure,80);assert.throws(()=>s.finishSimulation('op',claimed.token,{outcome:'ACKNOWLEDGED',jobId:'job'}));assert.throws(()=>s.claimSimulation('op'));assert.throws(()=>s.reserveOperation({...input,proposedEffect:{...input.proposedEffect,amount:70}}));}finally{other?.close();s.close();rmSync(dir,{recursive:true,force:true});}});
test('verified receipt and satisfaction persist atomically; historical replay is idempotent',()=>{const dir=mkdtempSync(join(tmpdir(),'mew-delivery-')),path=join(dir,'db.sqlite');let s=setup(path);try{s.reserveOperation(input);const args=receipt(s);assert.equal(s.acceptDelivery(args).position.satisfied,1);s.close();s=new OperationStore(path);assert.equal(s.acceptDelivery({...args,nowMs:999999}).idempotent,true);assert.equal(s.read().position('o').satisfied,1);assert.equal(s.read().position('o').exposure,80);assert.throws(()=>s.acceptDelivery({...args,envelope:{...args.envelope,signature:'A'.repeat(86)}}));assert.throws(()=>s.bindAcceptedDelivery({...args.envelope.payload,keyId:'rotated'}));}finally{s.close();rmSync(dir,{recursive:true,force:true});}});
test('failed delivery transition rolls receipt back; bad signature never writes',()=>{const s=setup();try{s.reserveOperation(input);const args=receipt(s);assert.throws(()=>s.acceptDelivery({...args,artifactBytes:Buffer.from('tampered')}));assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM delivery_receipts').get().n,0);s.transact(k=>k.observe({claimId:'refund-fixture',effectId:'e',source:'cardano',type:'released',evidence:{verified:true,simulated:true}}));assert.throws(()=>s.acceptDelivery(args));assert.equal(s.db.prepare('SELECT COUNT(*) AS n FROM delivery_receipts').get().n,0);}finally{s.close();}});
test('live library cannot dispatch fixtures; principal and job identities cannot be repurposed',()=>{const s=setup(':memory:',{mode:'live'});try{s.reserveOperation(input);assert.throws(()=>s.claimSimulation('op'));assert.throws(()=>s.recoverInterrupted());assert.throws(()=>s.reserveOperation({...input,principal:'other'}));const args=receipt(s);s.transact(k=>k.createObjective({...objective,id:'other-objective',semanticKey:'other-key'}));s.transact(k=>k.evaluate({objectiveId:'other-objective',proposedEffect:{...input.proposedEffect,id:'other-effect',semanticKey:'other-key'}}));const {version,receiptId,issuedAtMs,expiresAtMs,...expected}=args.envelope.payload;assert.throws(()=>s.bindAcceptedDelivery({...expected,keyId:'rotated-key',objectiveId:'other-objective',effectId:'other-effect'}));assert.throws(()=>s.reset());}finally{s.close();}});

test('simulation worker timeout retains exposure and never invokes provider again',async()=>{const {runSimulationOperation}=await import('../src/server/simulation-worker.mjs');const s=setup();let calls=0;try{s.reserveOperation(input);const result=await runSimulationOperation(s,'op',()=>{calls++;return new Promise(()=>{});},{timeoutMs:10});assert.equal(result.status,'UNKNOWN');assert.equal(s.read().position('o').exposure,80);await assert.rejects(runSimulationOperation(s,'op',()=>{calls++;return {jobId:'new-job'};}));assert.equal(calls,1);}finally{s.close();}});
test('live worker rejects before any external callback',async()=>{const {runSimulationOperation}=await import('../src/server/simulation-worker.mjs');const s=setup(':memory:',{mode:'live'});let calls=0;try{s.reserveOperation(input);await assert.rejects(runSimulationOperation(s,'op',()=>{calls++;return {jobId:'job'};}));assert.equal(calls,0);}finally{s.close();}});
test('released or delivered reservation cannot dispatch stale READY outbox',async()=>{const {runSimulationOperation}=await import('../src/server/simulation-worker.mjs');for(const type of ['released','delivery.verified','unknown','committed','settled']){const s=setup();let calls=0;try{s.reserveOperation(input);s.transact(k=>k.observe({claimId:`state-${type}`,effectId:'e',source:type==='delivery.verified'?'merchant':type==='unknown'?'host':'cardano',type,evidence:{verified:true,simulated:true}}));await assert.rejects(runSimulationOperation(s,'op',()=>{calls++;return {jobId:'job'};}));assert.equal(calls,0);assert.equal(s.operation('op').status,'READY');}finally{s.close();}}});
