import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,createHash,sign} from 'node:crypto';
import {OperationStore} from '../src/server/operation-store.mjs';import {OperatorService,operatorTokenDigest} from '../src/server/operator-service.mjs';import {deliveryReceiptBytes} from '../src/adapters/delivery-receipt.mjs';
const token='fixture-token-not-secret-'.repeat(3);
function fixture({revoked=false,actions=['read','reserve','accept-delivery'],expiresAtMs=3000,keyRevoked=false,clock=()=>1500}={}){const store=new OperationStore(':memory:',{mode:'live'});store.transact(k=>{k.createObjective({id:'own',principal:'owner',semanticKey:'own',quantity:1,maxExposure:100});k.createObjective({id:'other',principal:'other-owner',semanticKey:'other',quantity:1,maxExposure:100});});const pair=generateKeyPairSync('ed25519'),policy=[{principal:'owner',tokenDigest:operatorTokenDigest(token),expiresAtMs,revoked,actions}],providerKeys=[{provider:'vendor',keyId:'key',publicKey:pair.publicKey,notBeforeMs:1000,expiresAtMs:3000,revoked:keyRevoked}];const service=new OperatorService({store,policy,providerKeys,clock});return {store,service,pair,policy,providerKeys};}
const proposal={operationId:'op',objectiveId:'own',proposedEffect:{id:'effect',semanticKey:'own',provider:'vendor',type:'payment',amount:80}};
test('operator principal scopes actions and cannot impersonate request ownership',()=>{const {store,service}=fixture();try{assert.equal(service.reserve(token,proposal).decision,'ALLOW');assert.equal(service.read(token,'own').exposure,80);assert.throws(()=>service.read(token,'other'));assert.throws(()=>service.reserve(token,{...proposal,principal:'other-owner'}));assert.throws(()=>service.read('wrong-token'.repeat(5),'own'));}finally{store.close();}});
test('revoked expired and read-only credentials fail before reservations',()=>{for(const opts of [{revoked:true},{expiresAtMs:1500},{actions:['read']}]){const {store,service}=fixture(opts);try{assert.throws(()=>service.reserve(token,proposal));assert.equal(store.read().position('own').exposure,0);}finally{store.close();}}});
test('provider signature uses enrolled key and revoked key is rejected',()=>{for(const keyRevoked of [false,true]){const {store,service,pair}=fixture({keyRevoked});try{service.reserve(token,proposal);const bytes=Buffer.from('operator-accepted fixture'),artifactSha256=createHash('sha256').update(bytes).digest('hex'),expected={keyId:'key',principal:'owner',objectiveId:'own',effectId:'effect',provider:'vendor',jobId:'job',artifactSha256};store.bindAcceptedDelivery(expected);const payload={version:'mew-delivery-v1',receiptId:'receipt',...expected,issuedAtMs:1000,expiresAtMs:2000},envelope={payload,signature:sign(null,deliveryReceiptBytes(payload),pair.privateKey).toString('base64url')};if(keyRevoked){assert.throws(()=>service.acceptDelivery(token,{effectId:'effect',envelope,artifactBytes:bytes}));assert.equal(store.read().position('own').satisfied,0);}else assert.equal(service.acceptDelivery(token,{effectId:'effect',envelope,artifactBytes:bytes}).position.satisfied,1);}finally{store.close();}}});

test('invalid provider verification clock fails closed without observing delivery',()=>{let calls=0;const {store,service}=fixture({clock:()=>++calls<3?1500:NaN});try{service.reserve(token,proposal);store.bindAcceptedDelivery({keyId:'key',principal:'owner',objectiveId:'own',effectId:'effect',provider:'vendor',jobId:'job',artifactSha256:'a'.repeat(64)});assert.throws(()=>service.acceptDelivery(token,{effectId:'effect',envelope:{},artifactBytes:Buffer.alloc(0)}),/authorization denied/);assert.equal(store.read().position('own').satisfied,0);assert.equal(store.read().position('own').exposure,80);}finally{store.close();}});
