import test from 'node:test';
import assert from 'node:assert/strict';
import {addr} from './helpers/escrow-fixture.mjs';
import {observePreprodWallet} from '../src/integration/preprod-wallet.mjs';
const nowMs=1700000000000,address=addr(1),hash='a'.repeat(64);
const block={hash,height:123,slot:456,epoch:12,time:nowMs/1000};
const utxo={address,tx_hash:'b'.repeat(64),output_index:0,amount:[{unit:'lovelace',quantity:'9007199254740993'},{unit:'c'.repeat(56),quantity:'7'}]};
function config(overrides={}){return {address,nowMs,projectId:'preprod-fixture-only',fetchImpl:async url=>new Response(JSON.stringify(url.includes('utxos')?[utxo]:url.includes('parameters')?{epoch:12,min_fee_a:44,min_fee_b:155381,coins_per_utxo_size:'4310'}:block)),...overrides};}
test('bounded preprod read returns exact decimal balances without signing authority',async()=>{const r=await observePreprodWallet(config());assert.equal(r.balanceByUnit.lovelace,'9007199254740993');assert.equal(r.utxos.length,1);assert.equal(r.paymentsEnabled,false);assert.equal(r.activationReady,false);});
test('rejects invalid address or wrong-network credential before transport',async()=>{for(const patch of [{address:'addr_test1fake'},{projectId:'mainnet-key'}])await assert.rejects(observePreprodWallet(config({...patch,fetchImpl:()=>{throw Error('Must not fetch');}})));});
test('rejects stale and future chain context',async()=>{for(const time of [nowMs/1000-601,nowMs/1000+1])await assert.rejects(observePreprodWallet(config({fetchImpl:async()=>new Response(JSON.stringify({...block,time}))})));});
test('refuses incomplete pagination rather than returning a partial balance',async()=>{await assert.rejects(observePreprodWallet(config({fetchImpl:async url=>new Response(JSON.stringify(url.includes('utxos')?Array.from({length:100},(_,i)=>({...utxo,output_index:Number(new URL(url).searchParams.get('page'))*100+i})):url.includes('parameters')?{epoch:12,min_fee_a:44,min_fee_b:155381,coins_per_utxo_size:'4310'}:block))})),/pagination exceeds/);});
test('rejects duplicate inputs, malformed amounts and wrong owner',async()=>{for(const rows of [[utxo,utxo],[{...utxo,address:addr(2)}],[{...utxo,amount:[{unit:'lovelace',quantity:'-1'}]}]])await assert.rejects(observePreprodWallet(config({fetchImpl:async url=>new Response(JSON.stringify(url.includes('utxos')?rows:url.includes('parameters')?{epoch:12,min_fee_a:44,min_fee_b:155381,coins_per_utxo_size:'4310'}:block))})));});
test('rejects moving chain tip and oversized responses',async()=>{let blocks=0;await assert.rejects(observePreprodWallet(config({fetchImpl:async url=>new Response(JSON.stringify(url.includes('utxos')?[utxo]:url.includes('parameters')?{epoch:12,min_fee_a:44,min_fee_b:155381,coins_per_utxo_size:'4310'}:{...block,hash:++blocks>1?'d'.repeat(64):hash}))})));await assert.rejects(observePreprodWallet(config({fetchImpl:async()=>new Response(' '.repeat(262145))})));});
test('projects public evidence and never returns injected upstream fields',async()=>{const r=await observePreprodWallet(config({fetchImpl:async url=>new Response(JSON.stringify(url.includes('utxos')?[{...utxo,privateMetadata:'do-not-return'}]:url.includes('parameters')?{epoch:12,min_fee_a:44,min_fee_b:155381,coins_per_utxo_size:'4310',privateMetadata:'do-not-return'}:{...block,privateMetadata:'do-not-return',paymentSigning:true}))}));assert.deepEqual(r.latestBlock,block);assert.equal(JSON.stringify(r).includes('do-not-return'),false);assert.equal(r.latestBlock.paymentSigning,undefined);});
test('rejects redirected and substituted provider response URLs',async()=>{for(const patch of [{redirected:true},{url:'https://attacker.example/blocks/latest'},{url:'https://cardano-preprod.blockfrost.io/api/v0/other'}])await assert.rejects(observePreprodWallet(config({fetchImpl:async()=>{const r=new Response(JSON.stringify(block));for(const [key,value]of Object.entries(patch))Object.defineProperty(r,key,{value});return r;}})),/observation unavailable/);});
