import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { makeServer } from '../src/server/server.mjs';

const effect=id=>({objectiveId:'mission-report',proposedEffect:{id,semanticKey:'report-v1',provider:id,type:'payment',amount:550000,agent:id}});
async function start(options={}) {const server=makeServer({dbPath:':memory:',...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}`};}
const stop=s=>new Promise(r=>s.close(r));
async function post(url,path,body,extra={}) {const res=await fetch(url+path,{method:'POST',headers:{'content-type':'application/json',...extra},body:JSON.stringify(body)});return {status:res.status,body:await res.json()};}
test('competing HTTP reservations serialize with exactly one ALLOW',async()=>{const {server,url}=await start();try{const rs=await Promise.all([post(url,'/api/evaluate',effect('a')),post(url,'/api/evaluate',effect('b'))]);assert.equal(rs.filter(r=>r.body.decision==='ALLOW').length,1);assert.equal(rs.filter(r=>r.body.decision==='DEFER').length,1);}finally{await stop(server);}});
test('SQLite survives restart and retry cannot authorize another payment',async()=>{const dir=mkdtempSync(join(tmpdir(),'mew-'));const dbPath=join(dir,'test.sqlite');let s=await start({dbPath});try{await post(s.url,'/api/evaluate',effect('a'));await stop(s.server);s=await start({dbPath});const retry=await post(s.url,'/api/evaluate',effect('a'));assert.equal(retry.body.decision,'DEFER');const state=await (await fetch(s.url+'/api/state')).json();assert.equal(state.positions[0].reserved,550000);}finally{await stop(s.server);rmSync(dir,{recursive:true,force:true});}});
test('simulate is read-only and invalid observation rolls back',async()=>{const {server,url}=await start();try{await post(url,'/api/simulate',effect('a'));let s=await(await fetch(url+'/api/state')).json();assert.equal(s.effects.length,0);await post(url,'/api/evaluate',effect('a'));const invalid=await post(url,'/api/observe',{claimId:'bad',effectId:'a',source:'merchant',type:'payment.settled'});assert.equal(invalid.status,400);s=await(await fetch(url+'/api/state')).json();assert.equal(s.positions[0].reserved,550000);}finally{await stop(server);}});
test('demo claims labeled simulated; unknown delivery holds paid capacity',async()=>{const {server,url}=await start();try{await post(url,'/api/evaluate',effect('a'));const c=await post(url,'/api/observe',{claimId:'settled',effectId:'a',source:'cardano',type:'payment.settled'});assert.equal(c.body.claim.evidence.simulated,true);const b=await post(url,'/api/evaluate',effect('b'));assert.equal(b.body.decision,'DEFER');assert.equal(b.body.position.exposure,550000);}finally{await stop(server);}});
test('live API rejects unauthenticated requests and forged browser evidence',async()=>{const token='test-secret-'.repeat(4);const {server,url}=await start({demo:false,token});try{assert.equal((await fetch(url+'/api/state')).status,401);const r=await post(url,'/api/observe',{evidence:{verified:true}},{authorization:`Bearer ${token}`});assert.equal(r.status,403);assert.equal((await post(url,'/api/demo/reset',{},{authorization:`Bearer ${token}`})).status,403);}finally{await stop(server);}});
test('cross-origin mutations and wrong content type are rejected',async()=>{const {server,url}=await start();try{assert.equal((await post(url,'/api/evaluate',effect('a'),{origin:'https://evil.example'})).status,403);assert.equal((await fetch(url+'/api/evaluate',{method:'POST',body:'{}'})).status,415);}finally{await stop(server);}});
test('rehearsal checkpoints persist after restart and stale advances serialize',async()=>{const dir=mkdtempSync(join(tmpdir(),'mew-rehearsal-'));const dbPath=join(dir,'test.sqlite');let s=await start({dbPath});try{await post(s.url,'/api/rehearsal/reset',{scenario:'timeout'});const rs=await Promise.all([post(s.url,'/api/rehearsal/advance',{expectedStage:0}),post(s.url,'/api/rehearsal/advance',{expectedStage:0})]);assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(rs.filter(r=>r.status===400).length,1);await stop(s.server);s=await start({dbPath});const saved=await(await fetch(s.url+'/api/rehearsal')).json();assert.equal(saved.stage,1);assert.equal(saved.events.length,1);const original=await(await fetch(s.url+'/api/state')).json();assert.equal(original.effects.length,0);}finally{await stop(s.server);rmSync(dir,{recursive:true,force:true});}});
test('live mode forbids rehearsal fixtures',async()=>{const token='test-secret-'.repeat(4);const {server,url}=await start({demo:false,token});try{assert.equal((await fetch(url+'/api/rehearsal',{headers:{authorization:`Bearer ${token}`}})).status,403);assert.equal((await post(url,'/api/rehearsal/reset',{},{authorization:`Bearer ${token}`})).status,403);}finally{await stop(server);}});
