import test from 'node:test';
import assert from 'node:assert/strict';
import { reserveX402 } from '../src/adapters/x402.mjs';
import { Store } from '../src/server/store.mjs';
const mandate={objectiveId:'o',principal:'founder',semanticKey:'report',provider:'merchant',resourceUrl:'https://merchant.example/report',recipientAddress:'addr_test1fixture',maxAmount:1500000};
const quote=()=>({x402Version:2,resource:{url:mandate.resourceUrl},accepts:[{scheme:'exact',network:'cardano:preprod',asset:'lovelace',amount:'1500000',payTo:mandate.recipientAddress,maxTimeoutSeconds:60,extra:{assetTransferMethod:'default'}}]});
function setup(){const s=new Store(':memory:');s.transact(k=>k.createObjective({id:'o',principal:'founder',semanticKey:'report',quantity:1,maxExposure:3000000}));return s;}
test('x402 reservations persist and retries or competing agents cannot double purchase',()=>{const s=setup();try{const input={mandate,quote:quote(),effectId:'a',agent:'alpha'};assert.equal(reserveX402(s,input).decision,'ALLOW');assert.equal(reserveX402(s,input).decision,'DEFER');assert.equal(reserveX402(s,{...input,effectId:'b',agent:'beta'}).decision,'DEFER');assert.equal(s.read().position('o').exposure,1500000);}finally{s.close();}});
test('quote substitution and unsupported rails fail before reservation',()=>{for(const mutate of [q=>q.resource.url+='?other',q=>q.accepts[0].payTo+='other',q=>q.accepts[0].network='cardano:mainnet',q=>q.accepts[0].asset='USDM',q=>q.accepts[0].amount='1.5',q=>q.accepts[0].amount='9007199254740993',q=>q.accepts[0].extra.assetTransferMethod='masumi',q=>q.accepts.push({...q.accepts[0]}),q=>q.x402Version=1]){const s=setup();try{const q=quote();mutate(q);assert.throws(()=>reserveX402(s,{mandate,quote:q,effectId:'a',agent:'alpha'}));assert.equal(s.read().snapshot().effects.length,0);}finally{s.close();}}});
test('mandate principal cannot substitute objective owner',()=>{const s=setup();try{assert.throws(()=>reserveX402(s,{mandate:{...mandate,principal:'attacker'},quote:quote(),effectId:'a',agent:'alpha'}));assert.equal(s.read().position('o').exposure,0);}finally{s.close();}});
test('settlement with unknown delivery keeps objective occupied',()=>{const s=setup();try{reserveX402(s,{mandate,quote:quote(),effectId:'a',agent:'alpha'});s.transact(k=>k.observe({claimId:'fixture',effectId:'a',source:'cardano',type:'payment.settled',evidence:{verified:true,simulated:true}}));assert.equal(reserveX402(s,{mandate,quote:quote(),effectId:'b',agent:'beta'}).decision,'DEFER');}finally{s.close();}});
