import {createHash} from 'node:crypto';
import {prepareSupervisedExport} from './dataset.mjs';
import {verifyFrozenBenchmark} from './benchmark.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(k=>keys.includes(k));
const member=(v,options)=>options.includes(v);
export const defaultPersonalizationProfile=Object.freeze({organization:'mew-development',languages:['en','fr'],scope:'advisory-research',style:'concise-evidence-first',vocabulary:['economic-mandate','retained-exposure','preprod','delivery-evidence'],retrievalContext:['mew-owned-documentation'],authority:'advisory-only'});
export function planPersonalization({profile=defaultPersonalizationProfile,benchmarkRaw,benchmarkManifest,modelReceipt,reviewedExamples=[]}){
 if(!exact(profile,['organization','languages','scope','style','vocabulary','retrievalContext','authority'])||!/^[-a-z0-9]{1,64}$/.test(profile.organization??'')||profile.scope!=='advisory-research'||profile.authority!=='advisory-only'||!member(profile.style,['concise-evidence-first','explain-with-citations']))throw Error('Unsafe or invalid personalization profile');
 for(const [key,allowed] of [['languages',['en','fr']],['vocabulary',['economic-mandate','retained-exposure','preprod','delivery-evidence']],['retrievalContext',['mew-owned-documentation','tenant-approved-context']]]){
  if(!Array.isArray(profile[key])||!profile[key].length||profile[key].length>allowed.length||new Set(profile[key]).size!==profile[key].length||profile[key].some(x=>!member(x,allowed)))throw Error('Invalid profile vocabulary, language or retrieval context');
 }
 const benchmark=verifyFrozenBenchmark(benchmarkRaw,benchmarkManifest);
 if(!modelReceipt||!/^[-\w]+\/[-\w.]+$/.test(modelReceipt.modelId??'')||!/^[a-f0-9]{40}$/.test(modelReceipt.revision??'')||modelReceipt.license!=='apache-2.0'||modelReceipt.trustRemoteCode!==false||!/^\.local\/models\/[-\w.]+$/.test(modelReceipt.weightsLocation??'')||['.','..'].includes(modelReceipt.weightsLocation?.split('/').at(-1))||!exact(modelReceipt.files,Object.keys(modelReceipt.files??{}))||!Object.keys(modelReceipt.files).length||Object.values(modelReceipt.files).some(x=>!/^[a-f0-9]{64}$/.test(x)))throw Error('Invalid local model receipt');
 if(!Array.isArray(reviewedExamples)||reviewedExamples.length>10000)throw Error('Invalid reviewed examples');
 const forbiddenIds=new Set(benchmark.cases.map(x=>x.id)),forbiddenGroups=new Set(benchmark.cases.map(x=>x.lineageGroup)),forbiddenQuestions=new Set(benchmark.cases.map(x=>x.question.trim()));
 for(const e of reviewedExamples){
  if(forbiddenIds.has(e.id)||forbiddenGroups.has(e.groupId)||forbiddenGroups.has(e.lineageGroup)||forbiddenQuestions.has(e.input?.trim()))throw Error('Frozen benchmark contamination');
  if(e.reviewerType!=='human'||e.reviewStatus!=='approved'||e.reuseApproved!==true||!Array.isArray(e.evidence)||!e.evidence.length||e.evidence.some(r=>r.trainingConsent!=='approved'))throw Error('Human review and source training consent required');
 }
 const exportCheck=prepareSupervisedExport(reviewedExamples);
 return{schema:'mew.personalization-plan.v1',profile,profileSha256:sha(JSON.stringify(profile)),benchmarkSha256:benchmarkManifest.sha256,excludedCaseIds:[...forbiddenIds],excludedLineageGroups:[...forbiddenGroups],model:{id:modelReceipt.modelId,revision:modelReceipt.revision,receiptSha256:sha(JSON.stringify(modelReceipt))},trainingAuthorized:false,fineTuningReady:false,reviewedExampleCount:reviewedExamples.length,splitCounts:Object.fromEntries(Object.entries(exportCheck.splits).map(([k,v])=>[k,v.length])),exportReadyForReview:exportCheck.readyForReview,reviewProvenance:'Declared human reviewer fields require operator authentication; this planner cannot authenticate a reviewer.',blockers:[...(reviewedExamples.length?[]:['Separate human-approved, reuse-approved training examples are pending.']),exportCheck.reason,'Demonstrate generation failures with supporting evidence present before selecting SFT targets.','Validate chat rendering, prompt masking, context length and local memory feasibility before training.','Authenticate reviewer and tenant consent records; define retention and adapter access per organization.'],failureRouting:{missingFrenchEvidence:'Multilingual retrieval and exact-span coverage; not an SFT target.',schemaOrAdvisoryFailureWithEvidencePresent:'Candidate SFT target after human correction and leakage review.',unsupportedCitation:'Grounding review; JSON validity alone is insufficient.'},candidate:{status:'unexecuted-local-MLX-LoRA-plan',runtime:'mlx-lm==0.32.0',source:'https://github.com/ml-explore/mlx-lm/blob/main/mlx_lm/LORA.md',config:{model:modelReceipt.weightsLocation,fine_tune_type:'lora',data:'.local/personalization/reviewed-export',adapter_path:'.local/personalization/adapters',seed:42,num_layers:4,batch_size:1,iters:100,learning_rate:0.00001,max_seq_length:2048,mask_prompt:true,trust_remote_code:false,lora_parameters:{rank:8,dropout:0,scale:20}},dataFiles:{train:'train.jsonl',validation:'valid.jsonl',test:'test.jsonl'},configDelivery:'Write these verified MLX configuration keys to YAML only after review; no training command is executed.',moduleSelection:'Installed MLX architecture defaults must be inspected and recorded before run; no universal optimal rank claimed.'},evaluation:{languages:profile.languages,compare:'Same frozen cases and identical retrieval context for base versus adapter; these repeatedly used development cases are not a customer holdout.',metrics:['exact-span-coverage','schema-validity','citation-entailment','answer-correctness','false-acceptance','authority-violation'],promotion:'Fresh disjoint human-reviewed pilot holdout and zero authority violations required; no automatic deployment.'},externalResearchUse:'Papers, blogs, repositories and videos inform methods only; excluded from weight-training input.'};
}
