import test from 'node:test';
import assert from 'node:assert/strict';
import { runSuite, runScenario } from '../src/eval/runner.mjs';
import { SCENARIOS } from '../src/eval/scenarios.mjs';
import { gradeProvider } from '../src/eval/oracle.mjs';
import { buildReport, verifyReport, assertExpectedSuite, renderHTML, escapeHTML } from '../src/eval/report.mjs';
import { digest } from '../src/dispatch/contracts.mjs';

let cached;
async function report(){return cached??=buildReport(await runSuite());}
function resign(r){const {reportDigest,...body}=r;return {...body,reportDigest:digest(body)};}
test('45 scenarios grade receiver effects and detect bypass and deny-all negative controls',async()=>{const r=await report();assertExpectedSuite(r);assert.equal(r.results.length,45);const pick=(id,mode)=>r.results.find(x=>x.scenarioId===id&&x.mode===mode);assert.equal(pick('accepted-lost-response','guarded').metrics.acceptedPurchases,1);assert.equal(pick('accepted-lost-response','unguarded').metrics.acceptedPurchases,2);assert.equal(pick('concurrent','guarded').metrics.exposureByAsset['usd-cent'].peakCommitment,55);assert.equal(pick('concurrent','unguarded').metrics.exposureByAsset['usd-cent'].peakCommitment,110);assert.equal(pick('clean','deny-all').metrics.unjustifiedBlocks,1);assert.equal(pick('provider-outage','guarded').metrics.unresolvedOperations,1);assert.equal(pick('delayed-delivery','guarded').controls.usefulCompletion,'NOT_APPLICABLE');assert.equal(pick('bypass','guarded').controls.routedCoverage,'FAIL');assert.equal(pick('full-refund','guarded').metrics.exposureByAsset['usd-cent'].peakCommitment,55);});
test('fresh stores reproduce normalized schedules, including the concurrent winner',async()=>{for(const id of ['isolation','concurrent','crash-after-accept']){const s=SCENARIOS.find(x=>x.id===id);assert.deepEqual(await runScenario(s,'guarded'),await runScenario(s,'guarded'));}});
test('receiver oracle retains transient commitments even after a full refund',()=>{const records=[{key:'a',request:{asset:'usd-cent',amount:55,provider:'alpha',recipient:'supplier:alpha',principal:'owner',objectiveId:'report',semanticKey:'report-v1'},status:'refunded',delivered:false},{key:'b',request:{asset:'usd-cent',amount:49,provider:'beta',recipient:'supplier:beta',principal:'owner',objectiveId:'report',semanticKey:'report-v1'},status:'accepted',delivered:true}];const m=gradeProvider({records,events:[{key:'a',kind:'accepted'},{key:'a',kind:'refund'},{key:'b',kind:'accepted'},{key:'b',kind:'delivery'}],mandate:{id:'report',principal:'owner',asset:'usd-cent',semanticKey:'report-v1',quantity:1,maxExposure:100}});assert.equal(m.exposureByAsset['usd-cent'].cumulativeCharges,104);assert.equal(m.exposureByAsset['usd-cent'].currentCommitment,49);assert.equal(m.exposureByAsset['usd-cent'].peakCommitment,55);assert.equal(m.duplicateEquivalents,0);});
test('digest alteration and missing scenarios fail report verification',async()=>{const r=structuredClone(await report());r.reportDigest='0'.repeat(64);assert.throws(()=>verifyReport(r),/digest/);const missing=structuredClone(await report());missing.results.pop();assert.throws(()=>verifyReport(resign(missing)),/Missing scenario/);});
test('unsupported assurance claims, raw headers and inconsistent verdicts fail even with recomputed digests',async()=>{for(const mutate of [r=>r.results[0].controls.signedDelivery='PASS',r=>r.results[0].timeline[0].headers={authorization:'secret'},r=>r.results[0].pass=false,r=>r.results[0].metrics.exposureByAsset['usd-cent'].currentCommitment=0,r=>r.results[0].timeline=[],r=>r.results[0].metrics.unjustifiedBlocks=99]){const r=structuredClone(await report());mutate(r);assert.throws(()=>verifyReport(resign(r)));}});
test('HTML uses the verified report model and escapes hostile strings',async()=>{const r=await report();const html=renderHTML(r);assert.match(html,/14\/15/);assert.match(html,/NOT_IMPLEMENTED/);assert.match(html,/0\/0/);assert.equal(escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');assert.equal(html.includes('<script'),false);});
