import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { MEW } from '../src/core/mew.mjs';
import { Store } from '../src/server/store.mjs';
import { SandboxProvider } from '../src/adapters/sandbox-provider.mjs';
import { DispatchWorker } from '../src/dispatch/worker.mjs';
import { competingReservations, killDispatch } from '../src/eval/process.mjs';

const objective={id:'report',principal:'owner',semanticKey:'report-v1',asset:'usd-cent',quantity:1,maxExposure:100};
const proposal=(id='alpha',amount=55)=>({objectiveId:'report',proposedEffect:{id,semanticKey:'report-v1',provider:id,recipientAddress:'supplier:'+id,type:'payment',asset:'usd-cent',amount,agent:'buyer'}});
function fixture(){const dir=mkdtempSync(join(tmpdir(),'assurance-dispatch-'));const store=new Store(join(dir,'runtime.sqlite'));store.transact(k=>k.createObjective(objective));const provider=new SandboxProvider(join(dir,'provider.sqlite'));let now=1000;const worker=new DispatchWorker({store,provider,clock:()=>now,leaseMs:10});return {dir,store,provider,worker,setNow:n=>now=n,close(){store.close();provider.close();rmSync(dir,{recursive:true,force:true});}};}

test('reserve and outbox rollback together, old store upgrades and reopens',()=>{const f=fixture();try{assert.throws(()=>f.store.enqueue(proposal(),{beforeCommit:()=>{throw Error('rollback');}}),/rollback/);assert.equal(f.store.read().snapshot().effects.length,0);assert.equal(f.store.operations().length,0);const r=f.store.enqueue(proposal());assert.equal(r.decision,'ALLOW');assert.equal(r.operation.state,'READY');const reopened=new Store(join(f.dir,'runtime.sqlite'));assert.equal(reopened.operations().length,1);assert.equal(reopened.read().position('report').reserved,55);reopened.close();}finally{f.close();}});
test('lost response holds capacity and reconciliation finds only one acceptance',async()=>{const f=fixture();try{f.store.enqueue(proposal());await f.worker.tick('alpha',{fault:'lost-response'});assert.equal(f.store.operation('alpha').state,'UNKNOWN');assert.equal(f.store.read().position('report').reserved,55);assert.equal(f.store.enqueue(proposal('beta',49)).decision,'DEFER');await f.worker.tick('alpha');assert.equal(f.provider.records().length,1);assert.equal(f.store.operation('alpha').state,'OBSERVED');assert.equal(f.store.read().position('report').spent,55);}finally{f.close();}});
test('receiver rejects altered requests under an existing idempotency key',()=>{const f=fixture();try{f.store.enqueue(proposal());const op=f.store.operation('alpha');f.provider.submit(op.request,op.key);assert.throws(()=>f.provider.submit({...op.request,amount:56},op.key),/different request/);assert.equal(f.store.enqueue(proposal('alpha',56)).decision,'DENY');assert.equal(f.provider.records().length,1);}finally{f.close();}});
test('expired lease reconciles first and stale worker cannot write',()=>{const f=fixture();try{f.store.enqueue(proposal());const a=f.store.claim('alpha','a',1000,10);assert.equal(a.kind,'submit');const b=f.store.claim('alpha','b',1011,10);assert.equal(b.kind,'lookup');assert.throws(()=>f.store.recordUnknown('alpha',a.token,'a',1012,'timeout'),/Stale worker/);assert.equal(f.store.operation('alpha').state,'UNKNOWN');assert.equal(f.store.read().position('report').reserved,55);}finally{f.close();}});
test('outage is bounded without releasing funds; deny-all does not complete work',async()=>{const f=fixture();try{f.store.enqueue(proposal());await f.worker.tick('alpha',{fault:'outage'});for(let i=0;i<6;i++)await f.worker.tick('alpha',{fault:'outage'});assert.equal(f.store.operation('alpha').state,'UNKNOWN');assert.match(f.store.operation('alpha').reason,/review/);assert.equal(f.store.read().position('report').reserved,55);assert.equal(f.provider.records().length,0);}finally{f.close();}});
test('competing processes on one SQLite database admit one equivalent purchase',async()=>{const f=fixture();try{const decisions=await competingReservations(f.store.path,[proposal(),proposal('beta',49)]);assert.deepEqual(decisions.sort(),['ALLOW','DEFER']);assert.equal(f.store.operations().length,1);}finally{f.close();}});
for(const stage of ['crash-before-send','crash-after-accept']) test(stage+' survives a genuine child-process kill',async()=>{const f=fixture();try{f.store.enqueue(proposal());const result=await killDispatch(f.store.path,f.provider.path,'alpha',stage);assert.equal(result.signal,'SIGKILL');f.setNow(1011);await f.worker.tick('alpha');if(stage==='crash-before-send')await f.worker.tick('alpha');assert.equal(f.provider.records().length,1);assert.equal(f.store.operation('alpha').state,'OBSERVED');assert.equal(f.store.read().position('report').spent,55);}finally{f.close();}});
test('stale receiver send is deduplicated, mismatched observation rolls back',async()=>{const f=fixture();try{f.store.enqueue(proposal());const a=f.store.claim('alpha','old',1000,10);const b=f.store.claim('alpha','new',1011,10);const observation=f.provider.submit(a.request,a.key);f.provider.submit(b.request,b.key);assert.equal(f.provider.records().length,1);assert.throws(()=>f.store.recordObservation('alpha',b.token,'new',1012,{...observation,request:{...observation.request,amount:56}}),/does not match/);assert.equal(f.store.read().position('report').reserved,55);f.store.recordObservation('alpha',b.token,'new',1012,observation);assert.equal(f.store.read().position('report').spent,55);}finally{f.close();}});
test('pending and non-idempotent lookup never become permission to retry',async()=>{const f=fixture();try{f.store.enqueue(proposal());await f.worker.tick('alpha',{fault:'outage'});await f.worker.tick('alpha',{fault:'pending'});assert.equal(f.store.operation('alpha').state,'UNKNOWN');f.provider.supportsIdempotency=false;await f.worker.tick('alpha');assert.equal(f.store.operation('alpha').state,'UNKNOWN');assert.equal(f.provider.records().length,0);}finally{f.close();}});
test('refund and late delivery are synthetic observations, not fulfillment inferred from settlement',async()=>{const f=fixture();try{f.store.enqueue(proposal());await f.worker.tick('alpha');assert.equal(f.store.read().position('report').satisfied,0);f.provider.deliver(f.store.operation('alpha').key);f.worker.refresh('alpha');assert.equal(f.store.read().position('report').satisfied,1);assert.equal(f.store.read().snapshot().claims.every(c=>c.evidence.simulated),true);}finally{f.close();}});
test('pre-outbox database upgrades without losing an existing reservation',()=>{const dir=mkdtempSync(join(tmpdir(),'legacy-assurance-'));const path=join(dir,'runtime.sqlite');try{const legacy=new DatabaseSync(path);const k=new MEW();k.createObjective(objective);k.evaluate(proposal());legacy.exec('CREATE TABLE runtime (id INTEGER PRIMARY KEY, snapshot TEXT NOT NULL)');legacy.prepare('INSERT INTO runtime VALUES (1,?)').run(JSON.stringify(k.snapshot()));legacy.close();const migrated=new Store(path);assert.equal(migrated.read().position('report').reserved,55);assert.equal(migrated.enqueue(proposal()).decision,'DEFER');assert.equal(migrated.operations().length,0);assert.equal(migrated.db.prepare('PRAGMA user_version').get().user_version,1);migrated.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('receiver restart keeps deduplication and altered observation cannot partially refresh',async()=>{const f=fixture();try{f.store.enqueue(proposal());await f.worker.tick('alpha');const op=f.store.operation('alpha');const receiver=new SandboxProvider(f.provider.path);receiver.submit(op.request,op.key);assert.equal(receiver.records().length,1);receiver.close();const before=JSON.stringify(f.store.operation('alpha'));assert.throws(()=>f.store.refreshObservation('alpha',{...f.provider.lookup(op.key),requestDigest:'wrong'},1001),/does not match/);assert.equal(JSON.stringify(f.store.operation('alpha')),before);}finally{f.close();}});
test('dispatch rechecks persisted terms and rejects a released queued authorization',async()=>{for(const changed of ['payload','released']){const f=fixture();try{f.store.enqueue(proposal());if(changed==='payload')f.store.db.prepare('UPDATE dispatch_outbox SET request=? WHERE id=?').run(JSON.stringify({...f.store.operation('alpha').request,amount:99}),'alpha');else f.store.transact(k=>k.observe({claimId:'released',effectId:'alpha',source:'web2',type:'payment.released',evidence:{verified:true,simulated:true}}));await f.worker.tick('alpha');assert.equal(f.store.operation('alpha').state,'BLOCKED');assert.equal(f.provider.records().length,0);}finally{f.close();}}});
test('worker cannot dispatch through arbitrary adapters or shared ledger files',()=>{const f=fixture();try{assert.throws(()=>new DispatchWorker({store:f.store,provider:{submit(){}}}),/local simulator/);const same=new SandboxProvider(f.store.path);try{assert.throws(()=>new DispatchWorker({store:f.store,provider:same}),/independent/);}finally{same.close();}}finally{f.close();}});
